[package]
name = "rmpd"
version = "0.1.0"
authors = ["Olivier Lischer <olivier.lische@liolin.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
